services:
  streamlit:
    build:
      context: ./streamlit
    ports:
      - "8051:8051"
    depends_on:
      - api

  api:
    build:
      context: ./API
    ports:
      - "8050:8050"
    volumes:
      - ./API/data.json:/app/data.json
