services:
  streamlit:
    build:
      context: ./streamlit
    ports:
      - "69420:69420"
    depends_on:
      - api

  api:
    build:
      context: ./API
    ports:
      - "42069:42069"
    volumes:
      - ./API/data.json:/app/data.json
