version: '3.8'

services:
  streamlit:
    build:
      context: ./streamlit
    ports:
      - "8501:8501"
    depends_on:
      - api

  api:
    build:
      context: ./API
    ports:
      - "8000:8000"
    volumes:
      - ./API/data.json:/app/data.json
